lib/boxes_web/router.ex
defmodule BoxesWeb.Router do
  use BoxesWeb, :router

  pipeline :browser do
    plug(:accepts, ["html"])
    plug(:fetch_session)
    plug(:fetch_flash)
    plug(:protect_from_forgery)
    plug(:put_secure_browser_headers)
  end

  pipeline :api do
    plug(:accepts, ["json"])
  end

  scope "/", BoxesWeb do
    # Use the default browser stack
    pipe_through(:browser)

    get("/", PageController, :index)

    resources("/physical_boxes", PhysicalBoxController)
    resources("/physical_boxes_relationships", PhysicalRelationshipController)
    resources("/virtual_boxes", VirtualBoxController)
    resources("/virtual_boxes_relationships", VirtualRelationshipController)
  end

  # Other scopes may use custom stacks.
  # scope "/api", BoxesWeb do
  #   pipe_through :api
  # end
end

lib/boxes/physical/physical_relationship.ex
defmodule Boxes.Physical.PhysicalRelationship do
  @moduledoc """
  Physical Relationship model.
  """

  use Ecto.Schema
  import Ecto.Changeset

  alias Boxes.Physical.PhysicalBox

  schema "physical_boxes_relationships" do
    belongs_to(:box, PhysicalBox)
    belongs_to(:parent, PhysicalBox)

    timestamps()
  end

  @doc false
  def changeset(physical_relationship, attrs) do
    physical_relationship
    |> cast(attrs, [:box_id, :parent_id])
    |> validate_required([:box_id, :parent_id])
    |> foreign_key_constraint(:box_id)
    |> foreign_key_constraint(:parent_id)
  end
end

lib/boxes_web/controllers/physical_relationship_controller.ex
defmodule BoxesWeb.PhysicalRelationshipController do
  use BoxesWeb, :controller

  import Phoenix.HTML.Link

  alias BoxesWeb.QueryFilter

  alias Boxes.Physical
  alias Boxes.Physical.PhysicalRelationship

  def index(conn, _params) do
    physical_boxes_relationships = Physical.list_physical_boxes_relationships(%{preload: [:box, :parent]})
    render(conn, "index.html", physical_boxes_relationships: physical_boxes_relationships)
  end

  def new(conn, params) do
    changeset = Physical.change_physical_relationship(%PhysicalRelationship{})
    physical_boxes = Physical.list_physical_boxes()
    params = QueryFilter.changeset(%PhysicalRelationship{}, params)
    render(conn, "new.html", changeset: changeset, physical_boxes: physical_boxes, params: params)
  end

  def create(conn, %{"physical_relationship" => physical_relationship_params}) do
    case Physical.create_physical_relationship(physical_relationship_params) do
      {:ok, physical_relationship} ->
        conn
        |> put_flash(:info, ["Physical relationship created successfully.", link("Create new one?", to: Routes.physical_relationship_path(conn, :new))])
        |> redirect(to: Routes.physical_relationship_path(conn, :show, physical_relationship))

      {:error, %Ecto.Changeset{} = changeset} ->
        physical_boxes = Physical.list_physical_boxes()
        render(conn, "new.html", changeset: changeset, physical_boxes: physical_boxes, params: [])
    end
  end

  def show(conn, %{"id" => id}) do
    physical_relationship = Physical.get_physical_relationship!(id, %{preload: [:box, :parent]})
    render(conn, "show.html", physical_relationship: physical_relationship)
  end

  def edit(conn, %{"id" => id}) do
    physical_boxes = Physical.list_physical_boxes()
    physical_relationship = Physical.get_physical_relationship!(id)
    changeset = Physical.change_physical_relationship(physical_relationship)
    render(conn, "edit.html", physical_boxes: physical_boxes, physical_relationship: physical_relationship, changeset: changeset, params: [])
  end

  def update(conn, %{"id" => id, "physical_relationship" => physical_relationship_params}) do
    physical_relationship = Physical.get_physical_relationship!(id)

    case Physical.update_physical_relationship(
           physical_relationship,
           physical_relationship_params
         ) do
      {:ok, physical_relationship} ->
        conn
        |> put_flash(:info, "Physical relationship updated successfully.")
        |> redirect(to: Routes.physical_relationship_path(conn, :show, physical_relationship))

      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "edit.html",
          physical_relationship: physical_relationship,
          changeset: changeset
        )
    end
  end

  def delete(conn, %{"id" => id}) do
    physical_relationship = Physical.get_physical_relationship!(id)
    {:ok, _physical_relationship} = Physical.delete_physical_relationship(physical_relationship)

    conn
    |> put_flash(:info, "Physical relationship deleted successfully.")
    |> redirect(to: Routes.physical_relationship_path(conn, :index))
  end
end

lib/boxes_web/views/physical_relationship_view.ex
defmodule BoxesWeb.PhysicalRelationshipView do
  use BoxesWeb, :view

  def box_select(physical_boxes) do
    [{"", nil}] |> Enum.concat(physical_boxes |> Enum.map(&{&1.name, &1.id}))
  end
end

lib/boxes_web/templates/physical_relationship/edit.html.eex
<h2>Edit Physical relationship</h2>

<%= render "form.html", Map.put(assigns, :action, Routes.physical_relationship_path(@conn, :update, @physical_relationship)) %>

<span><%= link "Back", to: Routes.physical_relationship_path(@conn, :index) %></span>

lib/boxes_web/templates/physical_relationship/form.html.eex
<%= form_for @changeset, @action, fn f -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>

  <div class="form-group">
    <%= label f, :box_id, class: "control-label" %>
    <%= select f, :box_id, box_select(@physical_boxes), selected: @params[:box_id], class: "form-control" %>
    <%= error_tag f, :box_id %>
  </div>

  <div class="form-group">
    <%= label f, :parent_id, class: "control-label" %>
    <%= select f, :parent_id, box_select(@physical_boxes), selected: @params[:parent_id], class: "form-control" %>
    <%= error_tag f, :parent_id %>
  </div>

  <div class="form-group">
    <%= submit "Submit", class: "btn btn-primary" %>
  </div>
<% end %>

lib/boxes_web/templates/physical_relationship/index.html.eex
<h2>Listing Physical boxes relationships</h2>

<table class="table">
  <thead>
    <tr>
      <th></th>
      <th>Box</th>
      <th></th>
      <th>Parent</th>

      <th></th>
    </tr>
  </thead>
  <tbody>
<%= for physical_relationship <- @physical_boxes_relationships do %>
    <tr>
      <td><%= physical_relationship.box_id %></td>
      <td><%= physical_relationship.box.name %></td>
      <td><%= physical_relationship.parent_id %></td>
      <td><%= physical_relationship.parent.name %></td>

      <td class="text-right">
        <span><%= link "Show", to: Routes.physical_relationship_path(@conn, :show, physical_relationship), class: "btn btn-default btn-xs" %></span>
        <span><%= link "Edit", to: Routes.physical_relationship_path(@conn, :edit, physical_relationship), class: "btn btn-default btn-xs" %></span>
        <span><%= link "Delete", to: Routes.physical_relationship_path(@conn, :delete, physical_relationship), method: :delete, data: [confirm: "Are you sure?"], class: "btn btn-danger btn-xs" %></span>
      </td>
    </tr>
<% end %>
  </tbody>
</table>

<span><%= link "New Physical relationship", to: Routes.physical_relationship_path(@conn, :new) %></span>

lib/boxes_web/templates/physical_relationship/new.html.eex
<h2>New Physical relationship</h2>

<%= render "form.html", Map.put(assigns, :action, Routes.physical_relationship_path(@conn, :create)) %>

<span><%= link "Back", to: Routes.physical_relationship_path(@conn, :index) %></span>

lib/boxes_web/templates/physical_relationship/show.html.eex
<h2>Show Physical boxes relationship</h2>

<table class="table">
  <thead>
    <tr>
      <th></th>
      <th>Id</th>
      <th>Name</th>
      <th>Description</th>
      <th></th>
    </tr>
  </thead>

  <tr>
    <td><strong>Box</strong></td>
    <td><%= @physical_relationship.box_id %></td>
    <td><%= @physical_relationship.box.name %></td>
    <td><%= @physical_relationship.box.description %></td>
    <td class="text-right">
        <span><%= link "Show", to: Routes.physical_box_path(@conn, :show, @physical_relationship.box), class: "btn btn-default btn-xs" %></span>
    </td>
  </tr>

  <tr>
    <td><strong>Parent</strong></td>
    <td><%= @physical_relationship.parent_id %></td>
    <td><%= @physical_relationship.parent.name %></td>
    <td><%= @physical_relationship.parent.description %></td>
    <td class="text-right">
        <span><%= link "Show", to: Routes.physical_box_path(@conn, :show, @physical_relationship.parent), class: "btn btn-default btn-xs" %></span>
    </td>
  </tr>

</table>

<span><%= link "Edit", to: Routes.physical_relationship_path(@conn, :edit, @physical_relationship) %></span>
<span><%= link "Back", to: Routes.physical_relationship_path(@conn, :index) %></span>