lib/boxes_web/router.ex
defmodule BoxesWeb.Router do
  use BoxesWeb, :router

  pipeline :browser do
    plug(:accepts, ["html"])
    plug(:fetch_session)
    plug(:fetch_flash)
    plug(:protect_from_forgery)
    plug(:put_secure_browser_headers)
  end

  pipeline :api do
    plug(:accepts, ["json"])
  end

  scope "/", BoxesWeb do
    # Use the default browser stack
    pipe_through(:browser)

    get("/", PageController, :index)

    resources("/physical_boxes", PhysicalBoxController)
    resources("/physical_boxes_relationships", PhysicalRelationshipController)
    resources("/virtual_boxes", VirtualBoxController)
    resources("/virtual_boxes_relationships", VirtualRelationshipController)
  end

  # Other scopes may use custom stacks.
  # scope "/api", BoxesWeb do
  #   pipe_through :api
  # end
end

lib/boxes/virtual/virtual_relationship.ex
defmodule Boxes.Virtual.VirtualRelationship do
  @moduledoc """
  Virtual Relationship model.
  """

  use Ecto.Schema
  import Ecto.Changeset

  alias Boxes.Virtual.VirtualBox

  schema "virtual_boxes_relationships" do
    belongs_to(:box, VirtualBox)
    belongs_to(:parent, VirtualBox)

    timestamps()
  end

  @doc false
  def changeset(virtual_relationship, attrs) do
    virtual_relationship
    |> cast(attrs, [:box_id, :parent_id])
    |> validate_required([:box_id, :parent_id])
    |> foreign_key_constraint(:box_id)
    |> foreign_key_constraint(:parent_id)
  end
end

lib/boxes_web/controllers/virtual_relationship_controller.ex
defmodule BoxesWeb.VirtualRelationshipController do
  use BoxesWeb, :controller

  import Phoenix.HTML.Link

  alias BoxesWeb.QueryFilter

  alias Boxes.Virtual
  alias Boxes.Virtual.VirtualRelationship

  def index(conn, _params) do
    virtual_boxes_relationships = Virtual.list_virtual_boxes_relationships(%{preload: [:box, :parent]})
    render(conn, "index.html", virtual_boxes_relationships: virtual_boxes_relationships)
  end

  def new(conn, params) do
    changeset = Virtual.change_virtual_relationship(%VirtualRelationship{})
    virtual_boxes = Virtual.list_virtual_boxes()
    params = QueryFilter.changeset(%VirtualRelationship{}, params)
    render(conn, "new.html", changeset: changeset, virtual_boxes: virtual_boxes, params: params)
  end

  def create(conn, %{"virtual_relationship" => virtual_relationship_params}) do
    case Virtual.create_virtual_relationship(virtual_relationship_params) do
      {:ok, virtual_relationship} ->
        conn
        |> put_flash(:info, ["Virtual relationship created successfully.", link("Create new one?", to: Routes.virtual_relationship_path(conn, :new))])
        |> redirect(to: Routes.virtual_relationship_path(conn, :show, virtual_relationship))

      {:error, %Ecto.Changeset{} = changeset} ->
        virtual_boxes = Virtual.list_virtual_boxes()
        render(conn, "new.html", changeset: changeset, virtual_boxes: virtual_boxes, params: [])
    end
  end

  def show(conn, %{"id" => id}) do
    virtual_relationship = Virtual.get_virtual_relationship!(id, %{preload: [:box, :parent]})
    render(conn, "show.html", virtual_relationship: virtual_relationship)
  end

  def edit(conn, %{"id" => id}) do
    virtual_boxes = Virtual.list_virtual_boxes()
    virtual_relationship = Virtual.get_virtual_relationship!(id)
    changeset = Virtual.change_virtual_relationship(virtual_relationship)
    render(conn, "edit.html", virtual_boxes: virtual_boxes, virtual_relationship: virtual_relationship, changeset: changeset, params: [])
  end

  def update(conn, %{"id" => id, "virtual_relationship" => virtual_relationship_params}) do
    virtual_relationship = Virtual.get_virtual_relationship!(id)

    case Virtual.update_virtual_relationship(
           virtual_relationship,
           virtual_relationship_params
         ) do
      {:ok, virtual_relationship} ->
        conn
        |> put_flash(:info, "Virtual relationship updated successfully.")
        |> redirect(to: Routes.virtual_relationship_path(conn, :show, virtual_relationship))

      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "edit.html",
          virtual_relationship: virtual_relationship,
          changeset: changeset
        )
    end
  end

  def delete(conn, %{"id" => id}) do
    virtual_relationship = Virtual.get_virtual_relationship!(id)
    {:ok, _virtual_relationship} = Virtual.delete_virtual_relationship(virtual_relationship)

    conn
    |> put_flash(:info, "Virtual relationship deleted successfully.")
    |> redirect(to: Routes.virtual_relationship_path(conn, :index))
  end
end

lib/boxes_web/views/virtual_relationship_view.ex
defmodule BoxesWeb.VirtualRelationshipView do
  use BoxesWeb, :view

  def box_select(virtual_boxes) do
    [{"", nil}] |> Enum.concat(virtual_boxes |> Enum.map(&{&1.name, &1.id}))
  end
end

lib/boxes_web/templates/virtual_relationship/edit.html.eex
<h2>Edit Virtual relationship</h2>

<%= render "form.html", Map.put(assigns, :action, Routes.virtual_relationship_path(@conn, :update, @virtual_relationship)) %>

<span><%= link "Back", to: Routes.virtual_relationship_path(@conn, :index) %></span>

lib/boxes_web/templates/virtual_relationship/form.html.eex
<%= form_for @changeset, @action, fn f -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>

  <div class="form-group">
    <%= label f, :box_id, class: "control-label" %>
    <%= select f, :box_id, box_select(@virtual_boxes), selected: @params[:box_id], class: "form-control" %>
    <%= error_tag f, :box_id %>
  </div>

  <div class="form-group">
    <%= label f, :parent_id, class: "control-label" %>
    <%= select f, :parent_id, box_select(@virtual_boxes), selected: @params[:parent_id], class: "form-control" %>
    <%= error_tag f, :parent_id %>
  </div>

  <div class="form-group">
    <%= submit "Submit", class: "btn btn-primary" %>
  </div>
<% end %>

lib/boxes_web/templates/virtual_relationship/index.html.eex
<h2>Listing Virtual boxes relationships</h2>

<table class="table">
  <thead>
    <tr>
      <th></th>
      <th>Box</th>
      <th></th>
      <th>Parent</th>

      <th></th>
    </tr>
  </thead>
  <tbody>
<%= for virtual_relationship <- @virtual_boxes_relationships do %>
    <tr>
      <td><%= virtual_relationship.box_id %></td>
      <td><%= virtual_relationship.box.name %></td>
      <td><%= virtual_relationship.parent_id %></td>
      <td><%= virtual_relationship.parent.name %></td>

      <td class="text-right">
        <span><%= link "Show", to: Routes.virtual_relationship_path(@conn, :show, virtual_relationship), class: "btn btn-default btn-xs" %></span>
        <span><%= link "Edit", to: Routes.virtual_relationship_path(@conn, :edit, virtual_relationship), class: "btn btn-default btn-xs" %></span>
        <span><%= link "Delete", to: Routes.virtual_relationship_path(@conn, :delete, virtual_relationship), method: :delete, data: [confirm: "Are you sure?"], class: "btn btn-danger btn-xs" %></span>
      </td>
    </tr>
<% end %>
  </tbody>
</table>

<span><%= link "New Virtual relationship", to: Routes.virtual_relationship_path(@conn, :new) %></span>

lib/boxes_web/templates/virtual_relationship/new.html.eex
<h2>New Virtual relationship</h2>

<%= render "form.html", Map.put(assigns, :action, Routes.virtual_relationship_path(@conn, :create)) %>

<span><%= link "Back", to: Routes.virtual_relationship_path(@conn, :index) %></span>

lib/boxes_web/templates/virtual_relationship/show.html.eex
<h2>Show Virtual boxes relationship</h2>

<table class="table">
  <thead>
    <tr>
      <th></th>
      <th>Id</th>
      <th>Name</th>
      <th>Description</th>
      <th></th>
    </tr>
  </thead>

  <tr>
    <td><strong>Box</strong></td>
    <td><%= @virtual_relationship.box_id %></td>
    <td><%= @virtual_relationship.box.name %></td>
    <td><%= @virtual_relationship.box.description %></td>
    <td class="text-right">
        <span><%= link "Show", to: Routes.virtual_box_path(@conn, :show, @virtual_relationship.box), class: "btn btn-default btn-xs" %></span>
    </td>
  </tr>

  <tr>
    <td><strong>Parent</strong></td>
    <td><%= @virtual_relationship.parent_id %></td>
    <td><%= @virtual_relationship.parent.name %></td>
    <td><%= @virtual_relationship.parent.description %></td>
    <td class="text-right">
        <span><%= link "Show", to: Routes.virtual_box_path(@conn, :show, @virtual_relationship.parent), class: "btn btn-default btn-xs" %></span>
    </td>
  </tr>

</table>

<span><%= link "Edit", to: Routes.virtual_relationship_path(@conn, :edit, @virtual_relationship) %></span>
<span><%= link "Back", to: Routes.virtual_relationship_path(@conn, :index) %></span>