lib/boxes_web/router.ex
defmodule BoxesWeb.Router do
  use BoxesWeb, :router

  pipeline :browser do
    plug(:accepts, ["html"])
    plug(:fetch_session)
    plug(:fetch_flash)
    plug(:protect_from_forgery)
    plug(:put_secure_browser_headers)
  end

  pipeline :api do
    plug(:accepts, ["json"])
  end

  scope "/", BoxesWeb do
    # Use the default browser stack
    pipe_through(:browser)

    get("/", PageController, :index)

    resources("/physical_boxes", PhysicalBoxController)
    resources("/physical_boxes_relationships", PhysicalRelationshipController)
    resources("/virtual_boxes", VirtualBoxController)
    resources("/virtual_boxes_relationships", VirtualRelationshipController)
  end

  # Other scopes may use custom stacks.
  # scope "/api", BoxesWeb do
  #   pipe_through :api
  # end
end

lib/boxes/physical/physical_box.ex
defmodule Boxes.Physical.PhysicalBox do
  @moduledoc """
  Physical Box model.
  """

  use Ecto.Schema
  import Ecto.Changeset

  alias Boxes.Physical.PhysicalRelationship

  schema "physical_boxes" do
    field(:name, :string)
    field(:description, :string)

    timestamps()

    has_many(:physical_parents_relationships, PhysicalRelationship, foreign_key: :box_id)
    has_many(:physical_children_relationships, PhysicalRelationship, foreign_key: :parent_id)

    has_many(:physical_parents, through: [:physical_parents_relationships, :parent])
    has_many(:physical_children, through: [:physical_children_relationships, :box])
  end

  @doc false
  def changeset(physical_box, attrs) do
    physical_box
    |> cast(attrs, [:name, :description])
    |> validate_required([:name])
    |> unique_constraint(:name)
  end
end

lib/boxes_web/controllers/physical_box_controller.ex
defmodule BoxesWeb.PhysicalBoxController do
  use BoxesWeb, :controller

  import Phoenix.HTML.Link

  alias Boxes.Physical
  alias Boxes.Physical.PhysicalBox

  def index(conn, _params) do
    physical_boxes = Physical.list_physical_boxes(%{order_by: [:name]})
    render(conn, "index.html", physical_boxes: physical_boxes)
  end

  def new(conn, _params) do
    changeset = Physical.change_physical_box(%PhysicalBox{})
    render(conn, "new.html", changeset: changeset)
  end

  def create(conn, %{"physical_box" => physical_box_params}) do
    case Physical.create_physical_box(physical_box_params) do
      {:ok, physical_box} ->
        conn
        |> put_flash(:info, ["Physical box created successfully. ", link("Create new one?", to: Routes.physical_box_path(conn, :new))])
        |> redirect(to: Routes.physical_box_path(conn, :show, physical_box))
      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "new.html", changeset: changeset)
    end
  end

  def show(conn, %{"id" => id}) do
    physical_box = Physical.get_physical_box!(id, %{preload: [:physical_parents, :physical_children]})
    render(conn, "show.html", physical_box: physical_box)
  end

  def edit(conn, %{"id" => id}) do
    physical_box = Physical.get_physical_box!(id)
    changeset = Physical.change_physical_box(physical_box)
    render(conn, "edit.html", physical_box: physical_box, changeset: changeset)
  end

  def update(conn, %{"id" => id, "physical_box" => physical_box_params}) do
    physical_box = Physical.get_physical_box!(id)

    case Physical.update_physical_box(physical_box, physical_box_params) do
      {:ok, physical_box} ->
        conn
        |> put_flash(:info, "Physical box updated successfully.")
        |> redirect(to: Routes.physical_box_path(conn, :show, physical_box))
      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "edit.html", physical_box: physical_box, changeset: changeset)
    end
  end

  def delete(conn, %{"id" => id}) do
    physical_box = Physical.get_physical_box!(id)
    {:ok, _physical_box} = Physical.delete_physical_box(physical_box)

    conn
    |> put_flash(:info, "Physical box deleted successfully.")
    |> redirect(to: Routes.physical_box_path(conn, :index))
  end
end

lib/boxes_web/views/physical_box_view.ex
defmodule BoxesWeb.PhysicalBoxView do
  use BoxesWeb, :view
end

lib/boxes_web/templates/physical_box/edit.html.eex
<h2>Edit Physical box</h2>

<%= render "form.html", Map.put(assigns, :action, Routes.physical_box_path(@conn, :update, @physical_box)) %>

<span><%= link "Back", to: Routes.physical_box_path(@conn, :index) %></span>

lib/boxes_web/templates/physical_box/index.html.eex
<h2>Listing Physical boxes</h2>

<table class="table list-box">
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>

      <th></th>
    </tr>
  </thead>
  <tbody>
<%= for physical_box <- @physical_boxes do %>
    <tr>
      <td><%= physical_box.name %></td>
      <td><%= physical_box.description %></td>

      <td class="text-right">
        <span><%= link "Show", to: Routes.physical_box_path(@conn, :show, physical_box), class: "btn btn-default btn-xs" %></span>
        <span><%= link "Edit", to: Routes.physical_box_path(@conn, :edit, physical_box), class: "btn btn-default btn-xs" %></span>
        <span><%= link "Delete", to: Routes.physical_box_path(@conn, :delete, physical_box), method: :delete, data: [confirm: "Are you sure?"], class: "btn btn-danger btn-xs" %></span>
      </td>
    </tr>
<% end %>
  </tbody>
</table>

<span><%= link "New Physical box", to: Routes.physical_box_path(@conn, :new) %></span>

lib/boxes_web/templates/physical_box/new.html.eex
<h2>New Physical box</h2>

<%= render "form.html", Map.put(assigns, :action, Routes.physical_box_path(@conn, :create)) %>

<span><%= link "Back", to: Routes.physical_box_path(@conn, :index) %></span>

lib/boxes_web/templates/physical_box/show.html.eex
<h2>Show Physical box</h2>

<ul>

  <li>
    <strong>Name:</strong>
    <%= @physical_box.name %>
  </li>

  <li>
    <strong>Description:</strong>
    <%= @physical_box.description %>
  </li>

</ul>

<span><%= link "Edit", to: Routes.physical_box_path(@conn, :edit, @physical_box) %></span>
<span><%= link "Back", to: Routes.physical_box_path(@conn, :index) %></span>

<h3>List Parents</h3>

<%# If a (physical) box has more than one parent relationship, and thus is in more than one place at a time,
    it must be because there are copies of the box. %>
<%= if Enum.count(@physical_box.physical_parents_relationships) > 1 do %>
  There are <%= Enum.count(@physical_box.physical_parents_relationships) %>
  copies of <strong><%= @physical_box.name %></strong>.
<% end %>

<table class="table list-box">
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>

      <th></th>
    </tr>
  </thead>
  <tbody>
    <%# We use the relationships list instead of going directly through the parents list
        because we want to provide a "Delete Relationship" button. %>
    <%= for relationship <- @physical_box.physical_parents_relationships do %>
      <tr>
        <td><%= relationship.parent.name %></td>
        <td><%= relationship.parent.description %></td>

        <td class="text-right">
          <span><%= link "Show", to: Routes.physical_box_path(@conn, :show, relationship.parent), class: "btn btn-default btn-xs" %></span>
          <span><%= link "Remove", to: Routes.physical_relationship_path(@conn, :delete, relationship), method: :delete, data: [confirm: "Are you sure?"], class: "btn btn-danger btn-xs" %></span>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<span><%= link "Add parent", to: Routes.physical_relationship_path(@conn, :new, box_id: @physical_box) %></span>

<h3>List Children</h3>

<table class="table list-box">
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>

      <th></th>
    </tr>
  </thead>
  <tbody>
    <%# We use the relationships list instead of going directly through the children list
        because we want to provide a "Delete Relationship" button. %>
    <%= for relationship <- @physical_box.physical_children_relationships do %>
      <tr>
        <td><%= relationship.box.name %></td>
        <td><%= relationship.box.description %></td>

        <td class="text-right">
          <span><%= link "Show", to: Routes.physical_box_path(@conn, :show, relationship.box), class: "btn btn-default btn-xs" %></span>
          <span><%= link "Remove", to: Routes.physical_relationship_path(@conn, :delete, relationship), method: :delete, data: [confirm: "Are you sure?"], class: "btn btn-danger btn-xs" %></span>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<span><%= link "Add children", to: Routes.physical_relationship_path(@conn, :new, parent_id: @physical_box) %></span>