lib/boxes_web/router.ex
defmodule BoxesWeb.Router do
  use BoxesWeb, :router

  pipeline :browser do
    plug(:accepts, ["html"])
    plug(:fetch_session)
    plug(:fetch_flash)
    plug(:protect_from_forgery)
    plug(:put_secure_browser_headers)
  end

  pipeline :api do
    plug(:accepts, ["json"])
  end

  scope "/", BoxesWeb do
    # Use the default browser stack
    pipe_through(:browser)

    get("/", PageController, :index)

    resources("/physical_boxes", PhysicalBoxController)
    resources("/physical_boxes_relationships", PhysicalRelationshipController)
    resources("/virtual_boxes", VirtualBoxController)
    resources("/virtual_boxes_relationships", VirtualRelationshipController)
  end

  # Other scopes may use custom stacks.
  # scope "/api", BoxesWeb do
  #   pipe_through :api
  # end
end

lib/boxes/virtual/virtual_box.ex
defmodule Boxes.Virtual.VirtualBox do
  @moduledoc """
  Virtual Box model.
  """

  use Ecto.Schema
  import Ecto.Changeset

  alias Boxes.Virtual.VirtualRelationship

  schema "virtual_boxes" do
    field(:name, :string)
    field(:description, :string)

    timestamps()

    has_one(:virtual_parent_relationship, VirtualRelationship, foreign_key: :box_id)
    has_many(:virtual_children_relationships, VirtualRelationship, foreign_key: :parent_id)

    has_one(:virtual_parent, through: [:virtual_parent_relationship, :parent])
    has_many(:virtual_children, through: [:virtual_children_relationships, :box])
  end

  @doc false
  def changeset(virtual_box, attrs) do
    virtual_box
    |> cast(attrs, [:name, :description])
    |> validate_required([:name])
    |> unique_constraint(:name)
  end
end

lib/boxes_web/controllers/virtual_box_controller.ex
defmodule BoxesWeb.VirtualBoxController do
  use BoxesWeb, :controller

  import Phoenix.HTML.Link

  alias Boxes.Virtual
  alias Boxes.Virtual.VirtualBox

  def index(conn, _params) do
    virtual_boxes = Virtual.list_virtual_boxes(%{order_by: [:name]})
    render(conn, "index.html", virtual_boxes: virtual_boxes)
  end

  def new(conn, _params) do
    changeset = Virtual.change_virtual_box(%VirtualBox{})
    render(conn, "new.html", changeset: changeset)
  end

  def create(conn, %{"virtual_box" => virtual_box_params}) do
    case Virtual.create_virtual_box(virtual_box_params) do
      {:ok, virtual_box} ->
        conn
        |> put_flash(:info, ["Virtual box created successfully.", link("Create new one?", to: Routes.virtual_box_path(conn, :new))])
        |> redirect(to: Routes.virtual_box_path(conn, :show, virtual_box))
      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "new.html", changeset: changeset)
    end
  end

  def show(conn, %{"id" => id}) do
    virtual_box = Virtual.get_virtual_box!(id, %{preload: [:virtual_parent, :virtual_children]})
    render(conn, "show.html", virtual_box: virtual_box)
  end

  def edit(conn, %{"id" => id}) do
    virtual_box = Virtual.get_virtual_box!(id)
    changeset = Virtual.change_virtual_box(virtual_box)
    render(conn, "edit.html", virtual_box: virtual_box, changeset: changeset)
  end

  def update(conn, %{"id" => id, "virtual_box" => virtual_box_params}) do
    virtual_box = Virtual.get_virtual_box!(id)

    case Virtual.update_virtual_box(virtual_box, virtual_box_params) do
      {:ok, virtual_box} ->
        conn
        |> put_flash(:info, "Virtual box updated successfully.")
        |> redirect(to: Routes.virtual_box_path(conn, :show, virtual_box))
      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "edit.html", virtual_box: virtual_box, changeset: changeset)
    end
  end

  def delete(conn, %{"id" => id}) do
    virtual_box = Virtual.get_virtual_box!(id)
    {:ok, _virtual_box} = Virtual.delete_virtual_box(virtual_box)

    conn
    |> put_flash(:info, "Virtual box deleted successfully.")
    |> redirect(to: Routes.virtual_box_path(conn, :index))
  end
end

lib/boxes_web/views/virtual_box_view.ex
defmodule BoxesWeb.VirtualBoxView do
  use BoxesWeb, :view
end

lib/boxes_web/templates/virtual_box/edit.html.eex
<h2>Edit Virtual box</h2>

<%= render "form.html", Map.put(assigns, :action, Routes.virtual_box_path(@conn, :update, @virtual_box)) %>

<span><%= link "Back", to: Routes.virtual_box_path(@conn, :index) %></span>

lib/boxes_web/templates/virtual_box/form.html.eex
<%= form_for @changeset, @action, fn f -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>

  <div class="form-group">
    <%= label f, :name, class: "control-label" %>
    <%= text_input f, :name, class: "form-control" %>
    <%= error_tag f, :name %>
  </div>

  <div class="form-group">
    <%= label f, :description, class: "control-label" %>
    <%= text_input f, :description, class: "form-control" %>
    <%= error_tag f, :description %>
  </div>

  <div class="form-group">
    <%= submit "Submit", class: "btn btn-primary" %>
  </div>
<% end %>

lib/boxes_web/templates/virtual_box/index.html.eex
<h2>Listing Virtual boxes</h2>

<table class="table list-box">
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>

      <th></th>
    </tr>
  </thead>
  <tbody>
<%= for virtual_box <- @virtual_boxes do %>
    <tr>
      <td><%= virtual_box.name %></td>
      <td><%= virtual_box.description %></td>

      <td class="text-right">
        <span><%= link "Show", to: Routes.virtual_box_path(@conn, :show, virtual_box), class: "btn btn-default btn-xs" %></span>
        <span><%= link "Edit", to: Routes.virtual_box_path(@conn, :edit, virtual_box), class: "btn btn-default btn-xs" %></span>
        <span><%= link "Delete", to: Routes.virtual_box_path(@conn, :delete, virtual_box), method: :delete, data: [confirm: "Are you sure?"], class: "btn btn-danger btn-xs" %></span>
      </td>
    </tr>
<% end %>
  </tbody>
</table>

<span><%= link "New Virtual box", to: Routes.virtual_box_path(@conn, :new) %></span>

lib/boxes_web/templates/virtual_box/new.html.eex
<h2>New Virtual box</h2>

<%= render "form.html", Map.put(assigns, :action, Routes.virtual_box_path(@conn, :create)) %>

<span><%= link "Back", to: Routes.virtual_box_path(@conn, :index) %></span>

lib/boxes_web/templates/virtual_box/show.html.eex
<h2>Show Virtual box</h2>

<ul>

  <li>
    <strong>Name:</strong>
    <%= @virtual_box.name %>
  </li>

  <li>
    <strong>Description:</strong>
    <%= @virtual_box.description %>
  </li>

</ul>

<span><%= link "Edit", to: Routes.virtual_box_path(@conn, :edit, @virtual_box) %></span>
<span><%= link "Back", to: Routes.virtual_box_path(@conn, :index) %></span>

<h3>Parent</h3>

<table class="table list-box">
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>

      <th></th>
    </tr>
  </thead>
  <tbody>
    <%= if not is_nil(@virtual_box.virtual_parent) do %>
      <tr>
        <td><%= @virtual_box.virtual_parent.name %></td>
        <td><%= @virtual_box.virtual_parent.description %></td>

        <td class="text-right">
          <span><%= link "Show", to: Routes.virtual_box_path(@conn, :show, @virtual_box.virtual_parent), class: "btn btn-default btn-xs" %></span>
          <span><%= link "Remove", to: Routes.virtual_relationship_path(@conn, :delete, @virtual_box.virtual_parent_relationship), method: :delete, data: [confirm: "Are you sure?"], class: "btn btn-danger btn-xs" %></span>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= if is_nil(@virtual_box.virtual_parent) do %>
<span><%= link "Add parent", to: Routes.virtual_relationship_path(@conn, :new, box_id: @virtual_box) %></span>
<% end %>

<h3>List Children</h3>

<table class="table list-box">
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>

      <th></th>
    </tr>
  </thead>
  <tbody>
    <%# We use the relationships list instead of going directly through the children list
        because we want to provide a "Delete Relationship" button. %>
    <%= for relationship <- @virtual_box.virtual_children_relationships do %>
      <tr>
        <td><%= relationship.box.name %></td>
        <td><%= relationship.box.description %></td>

        <td class="text-right">
          <span><%= link "Show", to: Routes.virtual_box_path(@conn, :show, relationship.box), class: "btn btn-default btn-xs" %></span>
          <span><%= link "Remove", to: Routes.virtual_relationship_path(@conn, :delete, relationship), method: :delete, data: [confirm: "Are you sure?"], class: "btn btn-danger btn-xs" %></span>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<span><%= link "Add child", to: Routes.virtual_relationship_path(@conn, :new, parent_id: @virtual_box) %></span>